package com.togetherly.core.error

enum class ContentError {
    CATALOGUE_UNAVAILABLE,
    INVALID_CATALOGUE,
    QUEST_NOT_FOUND,
    PACK_NOT_FOUND,
    NO_QUEST_AVAILABLE,
    NO_AGE_COMPATIBLE_QUEST,
    NO_CONTEXT_COMPATIBLE_QUEST,
    ALL_CANDIDATES_IN_COOLDOWN,
}
