package com.togetherly.core.error

enum class ValidationError {
    INVALID_INPUT,
    MISSING_FAMILY_PROFILE,
    QUEST_NOT_FOUND,
    COMPLETION_NOT_FOUND,
    NO_ACTIVE_SESSION,
    ACTIVE_SESSION_CONFLICT,
    ACTIVE_SESSION_MISMATCH,
    NO_DAILY_SELECTION,
    REROLL_LIMIT_REACHED,
    PREMIUM_ACCESS_REQUIRED,
    INVALID_MEDIA,
    MEDIA_TOO_LARGE,
    INVALID_STATE,
}
